import { makeStyles } from "@material-ui/core/styles";

export const votingItemStyles = makeStyles(theme => ({
  root: {
    width: "100%",
    padding: 2,
    borderRadius: 12,
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    // position: "relative",
    // border: "4px solid transparent",
    // borderRadius: "16px",
    // background: "linear-gradient(orange, violet)",
    // backgroundClip: "padding-box",
    // padding: 10,
    // /* just to show box-shadow still works fine */
    // boxShadow: "0 3px 9px black, inset 0 0 9px white",

    // "&:after": {
    //   position: "absolute",
    //   top: "-4px",
    //   bottom: "-4px",
    //   left: "-4px",
    //   right: "-4px",
    //   background: "linear-gradient(red, blue)",
    //   content: '',
    //   zIndex: "-1",
    //   borderRadius: "16px",
    // }
  },
  rootMain: {
    background: "#151515",
    borderRadius: 10,
    padding: "32px 24px 32px 16px",
  },
  skeleton: {},
  sktImage: {},
  sktTitle: {},
  sktDays: {},
  sktInfo1: {},
  sktInfo2: {},
  sktButton: {},

  container: {},
  image: {
    width: 172,
    height: 112,
    marginRight: 28,
  },
  titleSection: {
    flex: 1,
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "104.5%",
    marginRight: 32,
  },
  title: {
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "20px",
    lineHeight: "120%",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    // width: "fit-content",
  },
  infoSection: {
    flex: 2,
  },
  quorumName: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 14,
    lineHeight: "104%",
  },
  quorumValue: {
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 18,
    lineHeight: "150%",
  },
  arWrap: {},
  progressBox: {
    width: 188,
    height: 24,
    background: "rgba(255,255,255,0.3)",
    position: "relative",
  },
  doneBar: {
    position: "absolute",
    top: 0,
    left: 0,
    height: 24,
  },
  barLabel: {
    position: "absolute",
    top: 2,
    left: 12,
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: 12,
    lineHeight: "160%",
    color: "#151515",
  },
  barValue: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: 16,
    lineHeight: "19px",
  },
  detailButton: {
    width: 156,
    height: 46,
    color: "#151515 !important",
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
  },
}));
